PROJECT_PRN221/Pages/Pages/AccountManager.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PROJECT_PRN211.Models;

namespace PROJECT_PRN211.Pages.Pages
{
    public class AccountManagerModel : PageModel
    {
        private Grocery_DatabaseContext _dbcontext = new Grocery_DatabaseContext();

        public List<Account> users = new List<Account>();

        public void OnGet()
        {
            users = _dbcontext.Accounts.Include(u => u.RIdNavigation).ToList();
        }

        public void OnPost(string aid, string role)
        {
            users = _dbcontext.Accounts.Include(u => u.RIdNavigation).ToList();
            Account acc = _dbcontext.Accounts.Where(a => a.AId == int.Parse(aid)).FirstOrDefault();
            if(role == "Admin")
            {
                acc.RId = 1;
                _dbcontext.Accounts.Update(acc);
                _dbcontext.SaveChanges();
            }
            if (role == "Employee")
            {
                acc.RId = 2;
                _dbcontext.Accounts.Update(acc);
                _dbcontext.SaveChanges();
            }

        }
    }
}

PROJECT_PRN221/Pages/Pages/HomeView.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using PROJECT_PRN211.Models;
using System.Text;

namespace PROJECT_PRN211.Pages.Pages
{

    public class HomeViewModel : PageModel
    {
        private Role role { get; set; }
        private Grocery_DatabaseContext _dbcontext = new Grocery_DatabaseContext();

        public string message { get; set; }

        public List<Product> products { get; set; }

        public List<CategoryId> categories { get; set; }
        public string SelectedCategory { get; set; }



        public void OnGet()
        {
            getdata();
            message = "Product Managenent";
            return;
        }


        public void getdata()
        {
            categories = _dbcontext.CategoryIds.Include(c => c.Products).ToList();
            products = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).OrderByDescending(p => p.DateExpiration).ToList();
        }
        public IActionResult OnGetCheckAuth()
        {
            getdata();
            ISession session = HttpContext.Session;
            var role_id_raw = session.Get("role_id");
            string role_id = Encoding.UTF8.GetString(role_id_raw);
            List<Role> roles = _dbcontext.Roles.Include(r => r.Features).Where(r => r.RId == int.Parse(role_id)).ToList();
            foreach (Role role in roles)
            {
                List<Feature> features = new List<Feature>();
                features = role.Features.ToList();
                foreach (Feature feature in features)
                {
                    if (feature.FeatureId == 1)
                    {
                        return RedirectToPage("Inventory");
                    }
                    else
                    {
                        message = "Bạn không được quyền vào trang này";
                        return this.Page();
                    }
                }
            }
            return this.Page();
        }
        [HttpGet]
        public IActionResult OnPostSortBy(string value)
        {
            categories = _dbcontext.CategoryIds.Include(c => c.Products).ToList();
            if (value == "name_des")
            {
                products = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).OrderByDescending(p => p.ProductName).ToList();
            }else if(value == "name_incre"){
                products = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).ToList();

            }else if(value == "price_h_L")
            {
                products = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).OrderByDescending(p => p.Price).ToList();
            }
            else
            {
                products = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).OrderByDescending(p => p.DateExpiration).ToList();
            }
            return this.Page();
        }
        public IActionResult OnPostDelete(int productId)
        {
            var bill_output = _dbcontext.BillOutputs.Where(b => b.ProductId == productId).ToArray();
            _dbcontext.BillOutputs.RemoveRange(bill_output);
            var pro = _dbcontext.Products.Where(p=> p.ProductId == productId).FirstOrDefault();
            if (pro != null)
            {
                _dbcontext.Products.Remove(pro);
                _dbcontext.SaveChanges();
                getdata();
                return this.Page();
            }
            else
            {
                return NotFound();
            }
        }
        public IActionResult OnGetCheckAuth2()
        {
            getdata();

            ISession session = HttpContext.Session;
            var role_id_raw = session.Get("role_id");
            string role_id = Encoding.UTF8.GetString(role_id_raw);
            List<Role> roles = _dbcontext.Roles.Include(r => r.Features).Where(r => r.RId == int.Parse(role_id)).ToList();
            foreach (Role role in roles)
            {
                List<Feature> features = new List<Feature>();
                features = role.Features.ToList();
                foreach (Feature feature in features)
                {
                    if (feature.FeatureId == 2)
                    {
                        return RedirectToPage("AccountManager");
                        
                    }
                    else
                    {
                        message = "Bạn không được quyền vào trang này";

                    }
                }
            }
            return this.Page();
        }

        public IActionResult OnPostFilter(string categoryName)
        {
            SelectedCategory = categoryName;
            categories = _dbcontext.CategoryIds.Include(c => c.Products).ToList();

            if (categoryName == "ALL")
            {
                products = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).OrderByDescending(p => p.DateExpiration).ToList();
            }
            else
            {
                products = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).Where(p => p.Category.CategoryName == categoryName ).OrderByDescending(p => p.DateExpiration).ToList();
            }

            return this.Page();
        }
        public IActionResult OnPostSearchByName(string ProductName)
        {
            categories = _dbcontext.CategoryIds.Include(c => c.Products).ToList();
            
            if (ProductName == string.Empty)
            {
                products = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).OrderByDescending(p => p.DateExpiration).ToList();
            }
            else
            {
                products = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).Where(p => p.ProductName == ProductName).OrderByDescending(p => p.DateExpiration).ToList();
            }
            if(products == null)
            {
                return NotFound() ;
            }
            return this.Page();
        }
    }
    }

PROJECT_PRN221/Pages/Pages/ImportProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PROJECT_PRN211.Models;

namespace PROJECT_PRN211.Pages.Pages
{
    public class ImportProductModel : PageModel
    {
        private Grocery_DatabaseContext _dbcontext = new Grocery_DatabaseContext();

        public List<CategoryId> categoryIds = new List<CategoryId>();
        public List<Supplier> suppliers = new List<Supplier>();
        public List<Product> products = new List<Product>();

        public int SelectedProduct { get; set; }

        public int SelectedCategory { get; set; }
        public int SelectedSupplier { get; set; }
        public void OnGet()
        {
            categoryIds = _dbcontext.CategoryIds.ToList();
            suppliers = _dbcontext.Suppliers.ToList();
        }

        public void OnPost(string CateoryID, string SupplierID) {
            SelectedCategory = int.Parse(CateoryID);
            SelectedSupplier = int.Parse(SupplierID);
            categoryIds = _dbcontext.CategoryIds.ToList();
            suppliers = _dbcontext.Suppliers.ToList();
            products = _dbcontext.Products.Where(p => p.SupplierId == int.Parse(SupplierID) && p.CategoryId == int.Parse(CateoryID)).ToList();
            
        }

        public void OnPostAdd(string ProductID, string amount)
        {
            SelectedProduct = int.Parse(ProductID);
            categoryIds = _dbcontext.CategoryIds.ToList();
            suppliers = _dbcontext.Suppliers.ToList();
            products = _dbcontext.Products.ToList();

            Product p = _dbcontext.Products.Where(p => p.ProductId == int.Parse(ProductID)).FirstOrDefault();
            p.Quantity = p.Quantity + int.Parse(amount);
            _dbcontext.Products.Update(p);
            _dbcontext.SaveChanges();

        }
    }
}

PROJECT_PRN221/Pages/Pages/Inventory.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PROJECT_PRN211.Models;

namespace PROJECT_PRN211.Pages.Pages
{
    public class InventoryModel : PageModel
    {
        private Grocery_DatabaseContext _dbcontext = new Grocery_DatabaseContext();

        public List<BillImport> billImports = new List<BillImport>();
        public void OnGet()
        {
            billImports = _dbcontext.BillImports.Include(b => b.Supplier).Include(b => b.Category).ToList();
        }
    }
}

PROJECT_PRN221/Pages/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PROJECT_PRN211.Models;
using Microsoft.AspNetCore.Http;


namespace PROJECT_PRN211.Pages.Pages
{
    public class LoginModel : PageModel
    {

        private Grocery_DatabaseContext _dbcontext = new Grocery_DatabaseContext();

        public string? message { get; set; }



        public void OnGet()
        {
        }

        public IActionResult OnPost(string username, string password)
        {

            if (username == null || password == null)
            {
                message = "Bạn phải nhập đầy đủ các trường";
                return this.Page();
            }


            Account? account = _dbcontext.Accounts.Where(a => a.Username == username).FirstOrDefault();
            if (account == null)
            {
                message = " tài khoản không tồn tại";
            }
            else
            {
                if (password == account.Password)
                {
                    if(account.RId == null)
                    {
                        message = "Bạn chưa được phép đăng nhập vào hệ thống";
                        return this.Page();
                    }

                    ISession session = HttpContext.Session;
                    session.SetString("role_id", account.RId.ToString());
                    message = "Đăng nhập thành công";
                    return RedirectToPage("HomeView");

                }
                else
                {
                    message = "sai tên tài khoản hoặc mật khẩu";
                    return this.Page();
                }
            }
            return this.Page();


        }

    }
}

PROJECT_PRN221/Pages/Pages/Register.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PROJECT_PRN211.Models;

namespace PROJECT_PRN211.Pages.Pages
{
    public class RegisterModel : PageModel
    {
        public string? message { get; set; }
        private Grocery_DatabaseContext _dbcontext = new Grocery_DatabaseContext();
        public void OnGet()
        {
        }
        public void OnPost(string username, string password, string re_password)
        {
            if ((username == null) || (password == null) || (re_password == null))
            {
                message = "Bạn phải nhập đầy đủ các trường";
                return;
            }

            if (password != re_password)
            {
                message = "Password và re_password không khớp yêu cầu nhập lại";
                return;
            }
            List<Account> accounts = new List<Account>();
            accounts = _dbcontext.Accounts.ToList();
            foreach (var item in accounts)
            {
                if (item.Username == username)
                {
                    message = "Tên tài khoản đã tồn tại vui lòng nhập tên tài khoản khác";
                    return;
                }
            }

            Account account = new Account();
            account.Username = username;
            account.Password = password;
            _dbcontext.Accounts.Add(account);
            _dbcontext.SaveChanges();
            message = "Đăng ký thành công";
            Redirect("/Pages/Login");
            return;
        }
    }
}

PROJECT_PRN221/Pages/Pages/ReportSales.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PROJECT_PRN211.Models;

namespace PROJECT_PRN211.Pages.Pages
{
    public class ReportSalesModel : PageModel
    {
        private Grocery_DatabaseContext _dbcontext = new Grocery_DatabaseContext();
        public List<BillOutput> billOutputs = new List<BillOutput>();
        public string massage { get; set; }
        public Product product { get; set; }

        public void OnGet(string ProductId, string Quantity)
        {
            product = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).Where(p => p.ProductId == int.Parse(ProductId)).FirstOrDefault();
            billOutputs  = _dbcontext.BillOutputs.Include(b=> b.Product).ToList();
        }
        public void OnPost(string ProductId, string Quantity)
        {
            product = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).Where(p => p.ProductId == int.Parse(ProductId)).FirstOrDefault();
            BillOutput billOutput = new BillOutput();
            billOutput.DateSell = DateTime.Now;
            billOutput.ProductId = int.Parse(ProductId);
            billOutput.Amount = int.Parse(Quantity);

            product.Quantity = product.Quantity - decimal.Parse(Quantity);
            _dbcontext.Products.Update(product);
            _dbcontext.BillOutputs.Add(billOutput);
            _dbcontext.SaveChanges();
            billOutputs = _dbcontext.BillOutputs.Include(b => b.Product).ToList();

        }

        //public void OnGet()
        //{

        //}
    }
}

PROJECT_PRN221/Pages/Pages/AccountManager.cshtml
@page
@model PROJECT_PRN211.Pages.Pages.AccountManagerModel
@{
}

<style>
    .result table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 10px;
    }

    .result th,
    .result td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
        width: auto;
    }
</style>
    <h1>List Employee</h1>
    <div class="result">
    <table width="500px" border="0">
        <thead>
            <tr>
                <td>Account</td>
                <td>User name</td>
                <td>Passowrd</td>
                <td>Role</td>
                <td>Admin</td>
                <td>Employee</td>
                <td>Save</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.users)
            {
                <tr>
                    <form method="post">
                    <td><input value="@item.AId" name="aid" readonly="readonly" /></td>
                    <td>@item.Username</td>
                    <td>@item.Password</td>
                    <td>
                            @((item.RIdNavigation == null) ? "chưa có chức vụ gì" : item.RIdNavigation.RName)
                    </td>
                    <td>
                        <input type="radio" name="role" value="Admin" />
                    </td>
                    <td>
                        <input type="radio" name="role" value="Employee" />
                    </td>
                    <td>
                        <input type="submit" value="Save" />
                    </td>
                    </form>
                </tr>
            }

        </tbody>
    </table>
    </div>
    
<a href="/Pages/HomeView">Back to home</a>

PROJECT_PRN221/Pages/Pages/HomeView.cshtml
@page 
@model PROJECT_PRN211.Pages.Pages.HomeViewModel
@{
}

<style>
    .result table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 10px;
    }

    .result th,
    .result td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
        width: auto;
    }
</style>
<div style="margin-top:5em; align-content:center" >
    <h3 style="margin-bottom:2em">@Model.message</h3>
    
    <div style="display:flex; flex-direction:row; width:81em; justify-content:space-between">
        <div style="display:flex; flex-direction:row; width:30em; justify-content:space-between">
            <form method="post" asp-page-handler="Filter">
                Category:
                <select name="categoryName">
                    <option value="ALL">ALL</option>
                    @foreach (var category in Model.categories)
                    {
                        <option value="@category.CategoryName" selected="@((Model.SelectedCategory == category.CategoryName) ? "selected" : null)">@category.CategoryName</option>
                    }
                </select>
                <input type="submit" name="Filter" value="Filter" />
            </form>

            <form method="post" asp-page-handler="SearchByName">
                <input type="text" name="ProductName" />
                <input type="submit" name="Search" value="Search" />
            </form>
        </div>
        
        <form method="post" asp-page-handler="SortBy">
            <label>Sory By:</label>
            <select name="value" onchange="onSortChange()">
                <option value="name_des">Sort by Name (A-Z) </option>
                <option value="name_incre">Sort by Name (Z-A) </option>
                <option value="price_h_L">Sort by Price (Low-High) </option>
                <option value="price_L_h">Sort by Price (High-Low)</option>
            </select>
            <input type="submit" name="Sort" value="Sort" />

        </form>
    </div>
    <div style="margin-top:2em" class="result">
        @if (Model.products is null)
        {
            <div>Choose category</div>
        }
        else
        {

            <table border="0" width="700px">
                <thead style="text-align:center">
                    <tr class="tr_table">
                        <td class="td_table">ProductID</td>
                        <td class="td_table">ProductName</td>
                        <td class="td_table">CategoryName</td>
                        <td class="td_table">SupplierName</td>
                        <td class="td_table">Unit</td>
                        <td class="td_table">Price</td>
                        <td class="td_table">Delete</td>
                        <td class="td_table">Sale</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var product in Model.products)
                    {
                        <tr class="tr_table">
                            <td class="td_table">@product.ProductId</td>
                            <td class="td_table">@product.ProductName</td>
                            <td class="td_table">@product.Category.CategoryName</td>
                            <td class="td_table">@product.Supplier.SupplierName</td>
                            <td class="td_table">@product.Quantity</td>
                            <td class="td_table">@product.Price</td>
                            <td class="td-table"><a method="Post" asp-page-handler="Delete" asp-route-productId="@product.ProductId">Delete</a></td>
                            <td class="td_table"><a href="ReportSales/@product.ProductId/@product.Quantity">Sale</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
    <script>
        function onSortChange() {
            var selectedValue = document.getElementById("sortby").value;
            //window.open.
        }
    </script>
</div>

PROJECT_PRN221/Pages/Pages/ImportProduct.cshtml
@page
@model PROJECT_PRN211.Pages.Pages.ImportProductModel
@{
}
<style>

    .item {
        display: flex;
        flex-direction: row;
        margin-top: 2em;
    }

        .item label {
            width: 8em;
        }

        .item input {
            flex: 1;
        }

    .nav-bar {
        width: 30%;
        height: 400px;
        align-content: center;
    }
</style>

    <div class="nav-bar">
        <h1>Nhập Thêm hàng</h1>
        <div class="nav-bar-component" style="width:80%; height:80%; align-content:center">
            <form method="post">

            <div class="item">
                <select name="CateoryID">
                    @foreach (var item in Model.categoryIds)
                    {
                        <option value="@item.CategeryId" selected="@((Model.SelectedCategory == item.CategeryId) ? "selected" : null)">@item.CategoryName</option>
                    }
                </select>
            </div>
            <div class="item">
                <select name="SupplierID">
                    @foreach (var supplier in Model.suppliers)
                {
                        <option value="@supplier.SupplierId" selected="@((Model.SelectedSupplier == supplier.SupplierId) ? "selected" : null)">@supplier.SupplierName</option>
                }
            </select>
            </div>
            <input type="submit" value="Tra cứu sản phẩm"/>
            </form>
        
        <form method="post" asp-page-handler="Add">
        @if(Model.products != null)
        {
            <div class="item">
                <select name="ProductID">
                    @foreach (var item in Model.products)
                    {
                        <option value="@item.ProductId" selected="@((Model.SelectedProduct == item.ProductId) ? "selected" : null)">@item.ProductName</option>
                    }
                </select>
            </div>
        }
           
      

            <div class="item">
                <label>Số lượng:</label>
                <input type="text" name="amount" />
            </div>
            <div style="margin-top:2em;">
                <input type="submit" value="Save" />
                <a href="/Pages/Inventory">Về kho</a>
            </div>
            </form>
            <a href="/Pages/HomeView">Back to home</a>

        </div>
    </div>

PROJECT_PRN221/Pages/Pages/Inventory.cshtml
@page
@model PROJECT_PRN211.Pages.Pages.InventoryModel
@{
}
<style>
    .result table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 10px;
    }

    .result th,
    .result td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
        width: auto;
    }
</style>
<h3>Inventory Management</h3>
<div style="margin-top:2em" class="result">
        <table border="1">
            <thead style="text-align:center">
                <tr class="tr_table">
                    <td class="td_table">Bill Import ID</td>
                    <td class="td_table">Import Date</td>
                    <td class="td_table">Số lượng</td>
                    <td class="td_table">Phân loại</td>
                    <td class="td_table">Nhà cung cấp</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.billImports)
                {
                    <tr class="tr_table">
                        <td class="td_table">@item.BillImportId</td>
                        <td class="td_table">@item.DateImport</td>
                        <td class="td_table">@item.Amount</td>
                        <td class="td_table">@item.Category.CategoryName</td>
                        <td class="td_table">@item.Supplier.SupplierName</td>
                    </tr>
                }
            </tbody>
            

        </table>
        <a href="/Pages/ImportProduct">Nhập thêm hàng</a>
        <a href="/Pages/HomeView">Back to home</a>
</div>

PROJECT_PRN221/Pages/Pages/Login.cshtml
@page
@model PROJECT_PRN211.Pages.Pages.LoginModel
@{
}

<style>

    .item {
        display: flex;
        flex-direction: row;
        margin-top: 2em;
    }

        .item label {
            width: 8em;
        }

        .item input {
            flex: 1;
        }

    .nav-bar {
        width: 30%;
        height: 400px;
        align-content: center;
    }
</style>
<div>
    <h1>LOGIN</h1>
    <h3>@Model.message</h3>

    <div class="nav-bar">
        <form method="post">
            <div>
                <div class="item">
                    <label>User name:</label>
                    <input type="text" name="username" />
                </div>
                <div class="item">
                    <label>Password:</label>
                    <input type="text" name="password" />
                </div>
                <div >
                    <input type="submit"  name="login" value="LOGIN"/>
                    <a href="/Pages/Register">Do you have account?</a>
                </div>
            </div>
        </form>
    </div>
</div>

PROJECT_PRN221/Pages/Pages/Register.cshtml
@page
@model PROJECT_PRN211.Pages.Pages.RegisterModel
@{
}
<style>
    
    .item {
        display:flex;
        flex-direction:row;
        margin-top:2em;
    }

    .item label {
        width:8em;
    }

    .item input {
        flex:1;
    }
    .nav-bar{
        width:30%;
        height:400px;
        
        align-content:center;
    }
</style>
<form method="post">
    <div class="nav-bar">
        <h1>REGISTER</h1>
        <h3>@Model.message</h3>
        <div class="nav-bar-component" style="width:80%; height:80%; align-content:center">
            <div class="item">
                <label>User name:</label>
                <input type="text" name="username" />
            </div>
            <div class="item">
                <label>Password:</label>
                <input type="text" name="password" />
            </div>
            <div class="item">
                <label>Re-password:</label>
                <input type="text" name="re_password" />
            </div>
            <div style="margin-top:2em;">
                <input type="submit" value="Đăng ký" />
                <a href="/Pages/Login">You already have account?</a>
            </div>
        </div>
    </div>
</form>
<script>
   
</script>

PROJECT_PRN221/Pages/Pages/ReportSales.cshtml
@page "/Pages/ReportSales/{ProductId}/{Quantity}"
@model PROJECT_PRN211.Pages.Pages.ReportSalesModel
@{
}
<style>

    .item {
        display: flex;
        flex-direction: row;
        margin-top: 2em;
    }

        .item label {
            width: 8em;
        }

        .item input {
            flex: 1;
        }

    .nav-bar {
        width: 80%;
        height: 100%;
        align-content: center;
    }
</style>
<div style="display:flex; flex-direction:row;">
    <div style="width:50em; height:80%;">
        @if (Model.product != null)
        {
            <div>
                <h1>Sản phẩm</h1>
                <h3>@Model.massage</h3>

                <div class="nav-bar">
                    <form method="Post">
                    <div>
                        <div class="item">
                            <label>Product ID:</label>
                            <input type="text" name="productid" readonly="readonly" value="@Model.product.ProductId" />
                        </div>
                        <div class="item">
                            <label>Product name:</label>
                            <input type="text" name="name" readonly="readonly" value="@Model.product.ProductName" />
                        </div>
                        <div class="item">
                            <label>Category:</label>
                            <input type="text" name="category" readonly="readonly" value="@Model.product.Category.CategoryName" />
                        </div>
                        <div class="item">
                            <label>Supplier:</label>
                            <input type="text" name="supllier" readonly="readonly" value="@Model.product.Supplier.SupplierName" />
                        </div>
                        <div class="item">
                            <label>Quantity:</label>
                            <input type="text" name="quantity" value="1" />
                        </div>
                        <div class="item">
                            <label>Unit price:</label>
                            <input type="text" name="unit" readonly="readonly" value="@Model.product.Price" />
                        </div>

                    </div>
                    <input type="submit" value="Bán" />
                    </form>
                </div>
                <a href="/Pages/HomeView">Back to home</a>
            </div>
        }

    </div>
    <div style="width:50em; height:80%;">
        <h3>Doanh số</h3>
        @if (Model.billOutputs != null)
        {
            <table width="100%">
                <thead>
                    <tr>
                        <td>Sản phẩm</td>
                        <td>Ngày bán</td>
                        <td>Số lượng</td>
                        <td>tổng giá</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.billOutputs)
                    {
                        <tr>
                            <td>@item.Product.ProductName</td>
                            <td>@item.DateSell</td>
                            <td>@item.Amount</td>
                            <td>@item.Amount * @item.Product.Price</td>
                        </tr>
                    }

                </tbody>
            </table>
        }
        else
        {
            <h1>Chưa có sản phẩm được bán</h1>
        }
    </div>
</div>