PROJECT_PRN221/Pages/Pages/HomeView.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using PROJECT_PRN211.Models;
using System.Text;

namespace PROJECT_PRN211.Pages.Pages
{

    public class HomeViewModel : PageModel
    {
        private Role role { get; set; }
        private Grocery_DatabaseContext _dbcontext = new Grocery_DatabaseContext();

        public string message { get; set; }

        public List<Product> products { get; set; }

        public List<CategoryId> categories { get; set; }
        public string SelectedCategory { get; set; }



        public void OnGet()
        {
            getdata();
            message = "Product Managenent";
            return;
        }


        public void getdata()
        {
            categories = _dbcontext.CategoryIds.Include(c => c.Products).ToList();
            products = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).OrderByDescending(p => p.DateExpiration).ToList();
        }
        public IActionResult OnGetCheckAuth()
        {
            getdata();
            ISession session = HttpContext.Session;
            var role_id_raw = session.Get("role_id");
            string role_id = Encoding.UTF8.GetString(role_id_raw);
            List<Role> roles = _dbcontext.Roles.Include(r => r.Features).Where(r => r.RId == int.Parse(role_id)).ToList();
            foreach (Role role in roles)
            {
                List<Feature> features = new List<Feature>();
                features = role.Features.ToList();
                foreach (Feature feature in features)
                {
                    if (feature.FeatureId == 1)
                    {
                        return RedirectToPage("Inventory");
                    }
                    else
                    {
                        message = "Bạn không được quyền vào trang này";
                        return this.Page();
                    }
                }
            }
            return this.Page();
        }
        [HttpGet]
        public IActionResult OnPostSortBy(string value)
        {
            categories = _dbcontext.CategoryIds.Include(c => c.Products).ToList();
            if (value == "name_des")
            {
                products = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).OrderByDescending(p => p.ProductName).ToList();
            }else if(value == "name_incre"){
                products = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).ToList();

            }else if(value == "price_h_L")
            {
                products = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).OrderByDescending(p => p.Price).ToList();
            }
            else
            {
                products = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).OrderByDescending(p => p.DateExpiration).ToList();
            }
            return this.Page();
        }
        public IActionResult OnPostDelete(int productId)
        {
            var bill_output = _dbcontext.BillOutputs.Where(b => b.ProductId == productId).ToArray();
            _dbcontext.BillOutputs.RemoveRange(bill_output);
            var pro = _dbcontext.Products.Where(p=> p.ProductId == productId).FirstOrDefault();
            if (pro != null)
            {
                _dbcontext.Products.Remove(pro);
                _dbcontext.SaveChanges();
                getdata();
                return this.Page();
            }
            else
            {
                return NotFound();
            }
        }
        public IActionResult OnGetCheckAuth2()
        {
            getdata();

            ISession session = HttpContext.Session;
            var role_id_raw = session.Get("role_id");
            string role_id = Encoding.UTF8.GetString(role_id_raw);
            List<Role> roles = _dbcontext.Roles.Include(r => r.Features).Where(r => r.RId == int.Parse(role_id)).ToList();
            foreach (Role role in roles)
            {
                List<Feature> features = new List<Feature>();
                features = role.Features.ToList();
                foreach (Feature feature in features)
                {
                    if (feature.FeatureId == 2)
                    {
                        return RedirectToPage("AccountManager");
                        
                    }
                    else
                    {
                        message = "Bạn không được quyền vào trang này";

                    }
                }
            }
            return this.Page();
        }

        public IActionResult OnPostFilter(string categoryName)
        {
            SelectedCategory = categoryName;
            categories = _dbcontext.CategoryIds.Include(c => c.Products).ToList();

            if (categoryName == "ALL")
            {
                products = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).OrderByDescending(p => p.DateExpiration).ToList();
            }
            else
            {
                products = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).Where(p => p.Category.CategoryName == categoryName ).OrderByDescending(p => p.DateExpiration).ToList();
            }

            return this.Page();
        }
        public IActionResult OnPostSearchByName(string ProductName)
        {
            categories = _dbcontext.CategoryIds.Include(c => c.Products).ToList();
            
            if (ProductName == string.Empty)
            {
                products = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).OrderByDescending(p => p.DateExpiration).ToList();
            }
            else
            {
                products = _dbcontext.Products.Include(p => p.Category).Include(p => p.Supplier).Where(p => p.ProductName == ProductName).OrderByDescending(p => p.DateExpiration).ToList();
            }
            if(products == null)
            {
                return NotFound() ;
            }
            return this.Page();
        }
    }
    }

PROJECT_PRN221/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PROJECT_PRN211</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PROJECT_PRN211.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Inventory Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Pages/HomeView" method="Get" asp-page-handler="CheckAuth">Inventory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Pages/HomeView" method="Get" asp-page-handler="CheckAuth2">Account manager</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Pages/Login">Log out</a>
                        </li>
                    </ul>
                </div>
                
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PROJECT_PRN211 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>